services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicine_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - medicine_network

  web:
    image: nginx:alpine
    container_name: medicine_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - medicine_network

  db:
    image: mysql:8.0
    container_name: medicine_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: medicine_tracking
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - medicine_network

volumes:
  db_data:

networks:
  medicine_network:
    driver: bridge
