version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicine_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - medicine_network

  web:
    image: nginx:alpine
    container_name: medicine_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - medicine_network

  db:
    image: mysql:8.0
    container_name: medicine_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: medicine_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - medicine_network

networks:
  medicine_network:
    driver: bridge
